export const VideoResult = {
    TOKEN_STOCK_OUT: "TOKEN_STOCK_OUT",
    SUCCESS: "SUCCESS",
    ERROR: "ERROR",
    TOKEN_REQUIRED: "TOKEN_REQUIRED",
    SOUND_FILLE_NOT_FOUND: "SOUND_FILLE_NOT_FOUND"
}